---
title: "Linear Regression Coding Assignment-3"
editor_options:
  chunk_output_type: inline
output: html_notebook
---
```{r}
library(ggplot2)
library(dplyr)
library(reshape)
```

```{r}
# Load the diabetes dataset: 
# 10 predictors which are age, gender (1-female, 2-male), body-mass index, average blood pressure, and six blood serum measurements and 1 response variable which is a quantitative measure of disease progression one year after baseline)
df = read.csv("D:/2nd sem/AAPS/Codes/Data/diabetes_new.csv", header = TRUE, stringsAsFactors = FALSE)
str(df)
```

```{r}
# Create a new feature called BMILEVEL using the BMI column and the following rules: BMI < 18.5 is underweight, 18.5 <= BMI <= 24.9 is healthy, 25 <= BMI <= 29.9 is overweight, BMI >= 30 is unhealthy
df = df %>% mutate(BMILEVEL = case_when(BMI < 18.5 ~ 'underweight', BMI >= 18.5 & BMI <= 24.9 ~ 'healthy',BMI >= 25.5 & BMI <= 29.9 ~ 'overweight', BMI >= 30 ~ 'unhealthy'))
str(df)
```


```{r}
# Convert 'GENDER' and 'BMILEVEL' columns to factors
categorical_cols = c('GENDER', 'BMILEVEL')
df[categorical_cols] = lapply(df[categorical_cols],as.factor)
str(df)
```

```{r}
# Create a list of continuous columns
continuous_cols = setdiff(colnames(df), categorical_cols)
continuous_cols
```

```{r}
# How many levels does the categorical variable *BMILEVEL* have? What is the reference level? 
contrasts(df$BMILEVEL)
levels(df$BMILEVEL)
```

```{r}
# Fit a linear model for predicting disease progression using BMILEVEL. Print the model's summary.
# How accurate is the model?
# Which level in BMILEVEL is most likely to not have a linear relationship with disease progression? What is the reason?
# How worse is the disease progression in unhealthy people compared to the healthy ones?
# How worse is the disease progression in unhealthy people compared to the overweight ones?
# Write down the individual model for each level in BMILEVEL
model = lm(data = df, Y ~ BMILEVEL)
summary(model)

model1 = lm(data = df, Y ~ BMILEVEL == "underweight")
summary(model1)
# "underweight" is not linear because the accuracy is in -ve

model2 = lm(data = df, Y ~ BMILEVEL == "unhealthy")
summary(model2)

model3 = lm(data = df, Y ~ BMILEVEL == "healthy")
summary(model3)

model4 = lm(data = df, Y ~ BMILEVEL == "overweight")
summary(model4)

#based on the provided linear regression model, the disease progression in unhealthy people is estimated to be 52.142 units worse than in healthy individuals. 

#the disease progression in unhealthy people is estimated to be 11.456 units worse than in overweight individuals. 

```


```{r}
# Fit a linear model for predicting disease progression using BMILEVEL and the blood serum measurements. 
# From the model summary, explain how you will find out which blood serum measurements are most likely to have a linear relationship with disease progression.
# Fit a model using BMILEVEL and the blood serum measurements identified in the previous question and compare its accuracy with the model fit using BMILEVEL and all blood serum measurements.


model = lm(data = df, Y~ BMILEVEL +S1 + S2 + S3 + S4 + S5 + S6 )
summary(model)

model1 = lm(data = df, Y ~ (BMILEVEL == "underweight") +S1 + S2 + S3 + S4 + S5 + S6)
summary(model1)

model2 = lm(data = df, Y ~ (BMILEVEL == "unhealthy") +S1 + S2 + S3 + S4 + S5 + S6)
summary(model2)

model3 = lm(data = df, Y ~ (BMILEVEL == "healthy") +S1 + S2 + S3 + S4 + S5 + S6)
summary(model3)

model4 = lm(data = df, Y ~ (BMILEVEL == "overweight") +S1 + S2 + S3 + S4 + S5 + S6)
summary(model4)


#Based on the provided output, it appears that S5 has a relatively high coefficient and a very low p-value, suggesting that it is a strong candidate for having a significant linear relationship with disease progression. 

```


```{r}
# Fit a linear model for predicting disease progression using BMI, age, BP, and gender. How accurate is the model? 
# According to the model, which gender has a worse disease progression? Explain why.
# For the same age, BP, and gender, decreasing BMI by 1 unit causes what change in the disease progression?
# For the same age and BP, which gender benefits better w.r.t. disease progressions by decreasing BMI by 1 unit. Explain.
model = lm(data = df, Y ~ BMI+AGE+ BP+ GENDER)
summary(model)
model1 = lm(data = df, Y ~ BMI+AGE+ BP+ (GENDER==1) + (GENDER == 2))
summary(model1)

# GENDER 2  has no impact on the disease progression, so it is the worst.

#BMI causes an equivalent change on the disease progression per unit.

#Irrespective of BMI change, Gender 1 is the one that contributes better since Gender 2 has no significant contribution towards disease progression.
```

```{r}
# Fit a linear model for predicting disease progression using BMI, age, BP, gender and interaction between BMI and gender. Is this model more accurate than the model without interaction between BMI and gender?


model = lm(data = df, Y ~ BMI + AGE + BP + GENDER + (BMI * GENDER))
summary(model)

# There is no significant difference as such. 


```
```{r}
# build model as BMI and Gender as the only predictors and make a plot. sets  of weights corresponding to male and female
model = lm(data = df, Y ~ BMI + GENDER )
summary(model)
```
```{r}
library(ggplot2)

```

```{r}
p = ggplot(df, aes(x=BMI,y=Y, color = GENDER))+
  geom_point(color='cyan',size=4)+ geom_smooth(method = "lm", se = FALSE, aes(group = GENDER))+ labs(title = "Scatter Plot",y='progression',x='BMI')+ 
  theme_minimal()
p
```






